# Screen
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

# Game Frame
GAME_FRAME_WIDTH = SCREEN_WIDTH - 100
GAME_FRAME_HEIGHT = SCREEN_HEIGHT - 100
HORIZONTAL_BORDER = GAME_FRAME_WIDTH//2
VERTICAL_BORDER = GAME_FRAME_HEIGHT//2

# Snake
STARTING_POSTION = [(0, 0), (-5, 0), (-10, 0), (-15, 0), (-20, 0)]
MOVE_DISTANCE = 5
UP = 90
DOWN = 270
RIGHT = 0
LEFT = 180

# Score Board
ALIGNEMENT = 'center'
FONT = ('Arial', 24, 'normal')